<form id="bankform" action="<?php echo Mage::getUrl('rma/index/savebankdetails'); ?>" method="post" onsubmit="return validateAccount()">
    <div class="field name-ifsc_code">
        <label for="ifsc_code" class="required"><em>*</em>IFSC Code</label>
        <div class="input-box">
            <input type="text" id="IFSC" name="ifsc_code" class="validate-alphanum validate-no-html-tags required-entry" value="<?php echo $this->getIfscCode(); ?>"/>
        </div>
    </div>
    <div class="field name-bankname">
        <label for="bankname" class="required"><em>*</em>Bank Name</label>
        <div class="input-box"><div class="loader"></div>
            <input type="text" id="bankname" name="bankname" value="<?php echo $this->getBankName(); ?>" title="Bank Name" maxlength="255" class="input-text validate-no-html-tags required-entry validate-alphanum-with-spaces">
        </div>
    </div>
    <div class="field name-account_num">
        <label for="account_num" class="required"><em>*</em>Account Number</label>
        <div class="input-box">
            <input type="text" id="account_num" name="account_no" minlength="12" maxlength="16" value="<?php echo $this->getAccountNumber(); ?>" title="Account Number" onkeypress="numberValidate(event)" class="input-text validate-no-html-tags validate-digits validate-greater-than-zero required-entry">
        </div>
    </div>
    <div class="field name-confirm_account">
        <label for="confirm_account" class="required"><em>*</em>Confirm Account Number</label>
        <div class="input-box">
            <input type="password" id="confirm_account" name="confirm_account" minlength="12" maxlength="16" value="<?php echo $this->getAccountNumber(); ?>" title="Confirm Account Number" onkeypress="numberValidate(event)" onblur="validateAccount()" class="input-text validate-no-html-tags validate-digits validate-greater-than-zero required-entry">
        </div>
    </div>
    <div id="msg">
        <span id='message'></span>
    </div>
    <div class="buttons-set">
        <p class="back-link"><a href="<?php echo Mage::getUrl('customer/account/'); ?>"><small>« </small>Back</a></p>
        <input type="submit" id="submit" class="button"/>        
    </div> 
        <input type="hidden" name="rmaItemId" value="<?php echo $this->getRequest()->getParam('rmaItemId')?>">
</form>
<style>
    .loader {
        border: 16px solid #f3f3f3;
        border-radius: 50%;
        border-top: 16px solid blue;
        border-bottom: 16px solid blue;
        width: 30px;
        height: 30px;
        -webkit-animation: spin 2s linear infinite;
        animation: spin 2s linear infinite;
    }

    @-webkit-keyframes spin {
        0% { -webkit-transform: rotate(0deg); }
        100% { -webkit-transform: rotate(360deg); }
    }

    @keyframes spin {
        0% { transform: rotate(0deg); }
        100% { transform: rotate(360deg); }
    }
</style>
<script type="text/javascript">
//<![CDATA[
    var customForm = new VarienForm('bankform');
    
    jQuery(document).ready(function()
    {
        jQuery('#msg').hide();
        jQuery('.loader').hide(); 
    });
    jQuery("#IFSC").keyup(function(){
        var ifsc = jQuery('#IFSC').val();
        if(ifsc.length === 11)
        {   
            jQuery('.loader').show(); 
            jQuery.ajax({           
                        type: "GET",
                        datatype : "application/json",
                        contentType: "text/plain",
                        url: "<?php echo $this->getUrl('rma/index/getBankDetails')?>",
                        data: {IFSC:ifsc},
                        success: function(response) {
                                JSON.stringify(response);
                                obj = JSON.parse(response);
                                jQuery('#bankname').val(obj.BANK);
                                jQuery('.loader').hide();                                           
                        },
                        error: function() {
                            alert("error");
                            jQuery('.loader').hide(); 
                        }
            });
        }
    });
   
    function validateAccount()
    {
        var accountNum     = jQuery('#account_num').val();
        var confirmAccount = jQuery('#confirm_account').val();
      
        if(Number.isInteger(accountNum) || Number.isInteger(confirmAccount))
        {
            jQuery('#msg').show();
            jQuery('#message').text('please insert valid number');
            return false;
        }
        if( !accountNum.empty() && !confirmAccount.empty())
        {
            if(accountNum.length<12 ||accountNum.length>16 || confirmAccount.length<12 || confirmAccount.length>16)
            {
                alert('please insert valid bank account number');
                return false;
            }
            if(accountNum != confirmAccount)
            {  
                jQuery('#msg').show(); 
                jQuery('#message').text('Wrong account Number inserted');
                return false;
            }
            else
            {
                jQuery('#msg').show(); 
                jQuery('#message').text('Matched');
            }
        }
        return true;        
    }
    function numberValidate(ele) 
    { 
        ele = (ele) ? ele : window.event;
        var charCode = (ele.which) ? ele.which : ele.keyCode;
        if (charCode > 31 && (charCode < 48 || charCode > 57))
        { 
            ele.preventDefault(); 
        }
    }
    
//]]>
</script>