<?php
//echo $this->getOrderLink();
//$customerLink = $this->getCustomerLink();
?>
<div class="entry-edit">
    <div class="entry-edit-head">
        <h4 class="icon-head head-shipping-method"><?php echo Mage::helper('rma')->__('Request Details') ?></h4>
    </div>
    <div class="fieldset">
        <div class="hor-scroll">
            <table cellspacing="0" class="form-list">
                <tr>
                    <td class="label"><label><?php echo Mage::helper('rma')->__('ID') ?></label></td>
                    <td class="value"><?php echo Mage::helper('rma')->__('#') . $this->getRmaData('entity_id') ?></td>
                </tr>
                <tr>
                    <td class="label"><label><?php echo Mage::helper('rma')->__('Order ID') ?></label></td>
                    <td class="value"><a href="<?php echo $this->getOrderLink() ?>"><?php echo Mage::helper('rma')->__('#') . $this->getRmaData('increment_id')?></a></td>
                </tr>
                <tr>
                    <td class="label"><label><?php echo Mage::helper('rma')->__('Customer Name') ?></label></td>
                    <td class="value">
                        <?php
//                            if ($customerLink) {
//                                echo '<a href="' . $customerLink . '">';
//                            }
                            echo $this->getRmaData('customer_name');
//                            if ($customerLink) {
//                                echo '</a>';
//                            }
                        ?>
                    </td>
                </tr>
                <tr>
                    <td class="label"><label><?php echo Mage::helper('rma')->__('Email Address') ?></label></td>
                    <td class="value"><a href="mailto:<?php echo $this->getRmaData('customer_email') ?>"><?php echo $this->getRmaData('customer_email') ?></a></td>
                </tr>
                <tr>
                    <td class="label"><label><?php echo Mage::helper('rma')->__('Contact Email Address') ?></label></td>
                    <td class="value"><a href="mailto:<?php echo $this->getRmaData('customer_email') ?>"><?php echo $this->getRmaData('customer_email') ?></a></td>
                </tr>
            </table>
        </div>
    </div>
</div>
