<?php $rma_id=Mage::registry('rma_data')->getId();
      $status=Mage::registry('rma_data')->getStatus();
      $oid=Mage::registry('rma_data')->getOrderId();
?>
<div class="entry-edit" id="rma-history-block">
    <div class="entry-edit-head">
        <h4 class="icon-head head-shipping-method"><?php echo Mage::helper('rma')->__('RMA History') ?></h4>
    </div>
    <div class="fieldset">
        <div id="history_form" class="rma-history-form">
            <span class="field-row">
                <label class="normal" for="history_comment"><?php echo Mage::helper('rma')->__('Comment Text') ?></label>
                <textarea name="comment[comment]" rows="3" cols="5" style="height:6em; width:99%;" id="history_comment"></textarea>
            </span>
            <div class="f-left">
                <?php //if ($this->canSendCommentEmail()): ?>
                    <input name="comment[is_customer_notified]" type="checkbox" id="history_notify" value="1" />
                    <label class="normal" for="history_notify"><?php echo Mage::helper('rma')->__('Notify Customer by Email') ?></label><br />
                <?php //endif; ?>
                     <input type="hidden" name="comment[rma_id]" id="rma_id" value="<?php echo $rma_id;?>">
                      <input type="hidden" name="comment[status]" id="status" value="<?php echo $status;?>">
<!--                      <input name="comment[is_visible_on_front]" type="checkbox" id="history_visible" value="1" /><label class="normal" for="history_visible"> <?php //echo Mage::helper('rma')->__('Visible on Frontend') ?></label>-->
                       <input name="order_id" type="hidden" value="<?php echo $oid; ?>">
                    </div>
            <div class="f-right">
                <?php echo $this->getChildHtml('submit_button') ?>
            </div>
            <div class="clear"></div>
            <?php if($this->getComments()): ?>
                <ul class="note-list">
                <?php foreach ($this->getComments() as $_item): ?>
                    <li>
                        <strong><?php echo $this->helper('core')->formatDate($_item->getCreatedAt(), 'medium') ?></strong>
                        <strong><?php echo $this->helper('core')->formatTime($_item->getCreatedAt(), 'medium') ?></strong>
                        <span class="separator">|</span>
                        <strong>
                            <?php if ($_item->getIsAdmin()): ?>
                                <?php echo $this->__('Customer Service')?>
                            <?php else: ?>
                                <?php echo $this->escapeHtml($_item->getCustomerName())?>
                            <?php endif; ?>
                        </strong><br/>
                        <small><?php echo $this->helper('rma')->__('Customer') ?>
                        <strong class="subdue">
                            <?php if ($_item->getIsCustomerNotified()): ?>
                            <?php echo $this->helper('rma')->__('Notified') ?>
                            <img src="<?php echo $this->getSkinUrl('images/ico_success.gif') ?>" width="16" height="16" alt="" />
                            <?php else: ?>
                            <?php echo $this->helper('rma')->__('Not Notified') ?>
                            <?php endif; ?>
                        </strong></small>
                        <?php if ($_item->getComment()): ?>
                            <br/><?php echo $this->escapeHtml($_item->getComment(), array('b','br','strong','i','u')) ?>
                        <?php endif; ?>
                    </li>
                <?php endforeach; ?>
                </ul>
            <?php endif ?>
        </div>
    </div>
</div>
