<?php
/* 
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
?>
<div class="page-title">
    <h1><?php echo $this->__('Create New RMA') ?></h1>
</div>
<?php $orderInfo = $this->getOrders();
if(count($orderInfo)>0): ?>
<select name="order" id="selectOrder">
<option value="">-- Select Orders --</option>
<?php foreach($orderInfo as $_order): ?>
<option value="<?php echo $_order->getId() ?>">
<?php echo $_order->getIncrementId().",".$_order->getGrandTotal() ?>
</option>
<?php endforeach; ?>
</select>
<?php endif; ?>

<table class="data-table orders" id="my-rma-table" >
    <col width="1" />
    <col width="1" />
    <col width="1" />
    <col width="1" />
    <col width="1" />
    <thead>
        <tr>
            <th class="number"><?php echo $this->__('PRODUCT NAME') ?></th>
            <th class="number"><?php echo $this->__('SKU') ?></th>
            <th class="number"><?php echo $this->__('QUANTITY') ?></th>
            <th class="total"><span class="nobr"><?php echo $this->__('PRICE') ?></span></th>
            <th class="view"><?php echo $this->__('ACTION'); ?></th>
        </tr>
    </thead>
    <tbody id="results">
            
    </tbody>
</table>

<script type="text/javascript">
    //<![CDATA[
    var $j = jQuery.noConflict();
    $j("#selectOrder").change( function() {
    var selectedOption = $j("#selectOrder option:selected");
    var selectedValue = selectedOption.val();
    $j.ajax({
            type: "POST",
            url: "<?php echo $this->getUrl('rma/index/productinfo')?>",
            data: {OrderId:selectedValue},
            success: function(response) {
                
                jQuery('#results').append(response);
            },
            error: function() {
                alert("error");
            }
        });
    });   
//]]>
</script>

