<?php
/* 
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
?>
<div class="page-title">
    <h1><?php echo $this->__('Create New RMA') ?></h1>
</div>
 <?php $orderInfo = $this->getOrders();
 if(count($orderInfo)>0): ?>
<select name="order" id="selectOrder">
 <option value="">-- Select Orders --</option>
 <?php foreach($orderInfo as $_order): ?>
 <option value="<?php echo $_order->getId() ?>">
 <?php echo $_order->getIncrementId().",".$_order->getGrandTotal() ?>
 </option>
 <?php endforeach; ?>
 </select>
 <?php endif; ?>

<table class="data-table orders" id="my-rma-table" >
    <col width="1" />
    <col width="1" />
    <col width="1" />
    <col width="1" />
    <col width="1" />
    <col width="1" />
    <col width="1" />
    <thead>
        <tr>
            <th class="number"><?php echo $this->__('PRODUCT NAME') ?></th>
            <th class="number"><?php echo $this->__('SKU') ?></th>
            <th class="number"><?php echo $this->__('QUANTITY') ?></th>
            <th class="total"><span class="nobr"><?php echo $this->__('PRICE') ?></span></th>
            <th class="status"><span class="nobr"><?php echo $this->__('RMA STATUS') ?></span></th>
            <th class="date"><?php echo $this->__('DATE'); ?></th>
            <th class="view"><?php echo $this->__('ACTION'); ?></th>
        </tr>
    </thead>
<!--    <tbody>
        <?php //$_odd = ''; ?>
        <?php //foreach ($orderInfo as $_return): ?>
        <tr>
            <td class="number"><?php //echo $_return->getId(); ?></td>
            <td class="number"><?php //echo $_return->getIncrementId(); ?></td>
            <td class="number"><?php //echo $_return->getProductId(); ?></td>
            <td class="total"><?php //echo Mage::helper('core')->currency($_return->getGrandTotal(), true, true); ?></td>
            <td class="status"><em><?php //echo $_return->getStatus() ?></em></td>
            <td class="date"><span class="nobr"><?php //echo Mage::helper('core')->formatDate($_return->getDateRequested());?></span></td>
            <td class="view"><a href="<?php //echo $this->getViewUrl($_return);?>"><span>View RMA</span></a></td>           
        </tr>
        <?php //endforeach; ?>
    </tbody>-->
</table>

<script type="text/javascript">
    //<![CDATA[
    var $j = jQuery.noConflict();
    $j("#selectOrder").change( function() {
    var selectedOption = $j("#selectOrder option:selected");
    var selectedValue = selectedOption.val();
    alert(selectedValue);
    $j.ajax({
            type: "POST",
            url: "<?php echo $this->getUrl('rma/index/productinfo')?>",
            data: {OrderId:selectedValue},
            success: function(msg) {
                alert(msg);
            },
            error: function() {
                alert("error");
            }
        });
    });
 
    
//]]>
</script>

