<div class="box-left">
    <?php echo $this->getChildHtml('request_details') ?>
</div>
<div class="box-right">
    <?php echo $this->getChildHtml('shipping_method') ?>
</div>
<div class="clear"></div>
<div class="box-left">
    <?php echo $this->getChildHtml('shipping_address') ?>
</div>
<div class="box-right">
    <?php echo $this->getChildHtml('return_address') ?>
</div>
<div class="clear"></div>
<div>
    <?php echo $this->getChildHtml('comments_history') ?>
</div>
