<?php
    $productInfo = Mage::registry('productInfo');    
    $alltrue = 1;
    $cancelType = isset($productInfo['is_cancel']) ? $productInfo['is_cancel'] : 0;
    if($cancelType):
        $alltrue = 0;
    else:
        foreach($productInfo as $item => $value ): 
            if($value['is_returnable']==1) { $alltrue = 0;break; }
        endforeach;
    endif;
?>
<table class="data-table orders" id="my-rma-table" >
    <?php if(empty($cancelType)): ?>
    <col width="1"/>
    <?php endif;?>
    <col width="1" />
    <col width="1" />
    <col width="1" />
    <col width="1" />
    <thead>
        <tr>
            <?php if(empty($cancelType)): ?>
            <th class="view"><?php echo $this->__('ACTION'); ?></th>
            <?php endif;?>
            <th class="number"><?php echo $this->__('PRODUCT NAME') ?></th>
            <th class=""><?php echo $this->__('SKU') ?></th>
            <th class="number"><?php echo $this->__('QUANTITY') ?></th>
            <th class="total"><span class="nobr"><?php echo $this->__('PRICE') ?></span></th>            
        </tr>
    </thead>
    
    <tbody id="ramTable">
    <?php
    $cnt = 0;
    if($alltrue==0):
    foreach($productInfo as $key => $value):
        $pid = $value['product_id'];
        if($productInfo['is_cancel'])
        {
            $value['is_returnable'] = 1;
        }
        if($value['is_returnable']): 
            $cnt++;
    ?> 
        <tr>
            <?php if(empty($cancelType)): ?>
            <td>   
            <input type="checkbox" name="products[<?php echo $pid;?>][checked]" id="checkbox_product_<?php echo $key ?>" value='1'>
            </td>
            <?php endif; ?>
            <td class="number"><?php echo $value['name']; ?></td>
            <td class=""><?php echo $value['sku']; ?></td>
            <td class="number"> 
                <?php
                    $readonly='readonly';
                    if(empty($cancelType)): 
                        $readonly='';
                    endif; ?>
                <input type="text" class="productQty" id="productQty_<?php echo $key;?>" name="products[<?php echo $pid;?>][qty_requested]" value="<?php echo round($value['qty_ordered']); ?>" <?php echo $readonly;?> data-pid="<?php echo $pid;?>" data-price="<?php echo $value['base_original_price'];?>" data-orderedqty="<?php echo $value['qty_ordered'];?>" data-name="<?php echo $value['name'];?>">
            </td>
            <td class="total" id="productPrice_<?php echo $pid;?>"><?php echo $value['base_row_total'] ?></td>
        </tr>            

        <?php $product_price = isset($value['base_original_price'])? $value['base_original_price']: '';
        ?>
        <input type="hidden" id="original_price_<?php echo $key;?>" name="original_price" value="<?php echo $product_price?>">
        <?php
        endif;
    endforeach;?>
           
    <?php        
    else: ?> 
        <tr>
            <td colspan="5" style="text-align: center; font-size: 12px;">Product cannot be return</td>
        </tr>
        <?php endif; ?>
        <tr id="notification-message" style="display:none">
            <td></td>
            <td></td>
            <td colspan="5" style="text-align: center; font-size: 12px; color: red;" id="notification"></td>
            <td></td>
        </tr>
        <tr id="notification-message1" style="display:none">
            <td></td>
            <td></td>
            <td colspan="5" style="text-align: center; font-size: 12px; color: red;" id="notification1"></td>
            <td></td>
        </tr>
        <tr>
            <td><label>Resolution</label></td>
            <td>
            <?php $resolution=Mage::helper('rma')->getAttributeOptionValues('resolution');?>
                <select name="resolution_type" id="resolution_type" class="validate-select resolution_type">
                    <option value="">-- Select Resolution --</option>
                    <?php 
                    $selected ='';
                    foreach ($resolution as $key => $value) {
                        if($cancelType && strtolower($key) === 'cancel' || $cancelType==0 && strtolower($key) !== 'cancel'): 
                            $selected = 'selected';
                    ?>        
                    <option value="<?php echo $key;?>" <?php echo $selected;?>>
                        <?php echo $value;?>
                    </option>
                    <?php
                        endif;
                    }?>
                </select>
            </td>
        </tr>
        <tr>
            <td><label>Delivery Status</label></td>
            <td>
              <?php                 
                $delivery_status=Mage::helper('rma')->getAttributeOptionValues('delivery_status');                
                ?>               
                <select name="delivery_status"  class="validate-select" id="delivery_status">
                    <option value="">-- Select condition --</option>
                    <?php 
                    foreach ($delivery_status as $key => $value) {
                        if($cancelType && strtolower($key) === 'not delivered' || $cancelType==0 && strtolower($key) !== 'not delivered'): 
                        $selected = 'selected';
                    ?>        
                    <option value="<?php echo $key;?>" <?php echo $selected;?>>
                        <?php echo $value;?>
                    </option>
                    <?php
                        endif;
                    }?>
                </select>  
                <input type="hidden" value="<?php echo $cancelType;?>" name="cancelType">             
            </td>
        </tr>
        <?php if(empty($cancelType)): ?>
        <tr>
            <td><label>Consignment No.</label></td>
            <td><input type="text" name="consign_number" class="required-entry"></td>
        </tr>
        <?php endif;?>
        <tr>
            <td><label>Reason</label></td>
            <td><input type="text" name="reason" class="required-entry"></td>
        </tr>
        
        <tr>
            <td>
                <input type="submit" id="submit">
            </td>
        </tr>
    </tbody>
</table>
<input type="hidden" name="count" id="cnt" value="<?php echo $cnt ?>">
<script type="text/javascript">
    //<![CDATA[
    var $j = jQuery.noConflict();  
    var cancelType = "<?php echo $cancelType;?>";
    
    $j(".productQty").change( function() 
    {
        var pid = $j(this).data('pid');
        var price = $j(this).data('price');
        var orderedQty = parseInt($j(this).data('orderedqty'));
        var productName = $j(this).data('name');
        var qty_requested = parseInt($j(this).val());
        
        if(qty_requested > orderedQty)
        {
            $j("#notification-message").show();
            $j("#notification").html("You can not return "+qty_requested+" "+productName);
        }
        else
        {
            $j("#notification").empty();
            $j('#productPrice_'+pid).empty();
            $j('#productPrice_'+pid).html(price*qty_requested);
        }
                              
    });   
//]]>
</script>