<?php

/* 
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
?>
<form id="bankform" action="<?php echo Mage::getUrl('rma/index/savebankdetails'); ?>" method="post">
<table>
<tr>
    <td><label>Bank Name</label></td>
    <td><input type="text" name="bankname" class="required-entry"/></td>
</tr>
<br/>
<tr>
    <td><label>Account Number</label></td>
    <td><input type="password" name="account_no" class="required-entry"/></td>
</tr>
<br/>
<tr>
    <td><label>IFSC Code</label></td>
    <td><input type="text" name="ifsc_code" class="required-entry"/></td>
</tr>
<br/>
<tr>
    <td></td>
    <td><input type="submit" id="submit"/></td>
</tr>
<br/>
</table>
    <input type="hidden" name="rmaItemId" value="<?php echo $this->getRequest()->getParam('rmaItemId')?>">
</form>

<script type="text/javascript">
    var customForm = new VarienForm('bankform'); 
</script>