<div class="page-title">
    <h1>
    <?php    
        $cancelType = $this->getCancelType();
        $action_name=Mage::app()->getRequest()->getActionName();       
        $rmaOrderId = $this->getRmaOrderId();
        $rmaOrdersCollection = $this->getRmaOrders();
        $rmaOrders = array_column($rmaOrdersCollection, 'order_id');
        $rmaOrdersItem = array_column($rmaOrdersCollection, 'itemcount', 'order_id');
        
        $title = ($cancelType) ? $this->__('Cancel Order') : $this->__('Create RMA');
        echo $title;
    ?>
    </h1>
</div>
<form id="requestForm" method="POST" action="<?php echo Mage::getUrl('rma/index/save'); ?>">
    <label><h4>Order Id : </h4></label>
    <?php 
    $orderInfo = $this->getOrders(1);
    if(count($orderInfo)>0) : ?>
    <select name="order" id="selectOrder" class="validate-select">
        <option value="">-- Select Orders --</option>
        <?php
            $selected = '';
            foreach($orderInfo as $_key=>$_order):
                if(!empty($rmaOrders)):
                    if(in_array($_order->getId(), $rmaOrders)):
                        if($_order->getTotalItemCount() == $rmaOrdersItem[$_order->getId()]):
                        unset($_order[$_key]);continue;
                        endif;
                    endif; 
                endif;
                if($rmaOrderId == $_order->getId()):
                    $selected = 'selected';
                endif;
                
        ?>
                <option value="<?php echo $_order->getId() ?>" <?php echo $selected;?>>
                    <?php echo $_order->getIncrementId()?>
                </option>
        <?php $selected = ''; endforeach;?>
    </select>
    <?php endif; ?>

    <div id="results"></div>

</form>

<script type="text/javascript" >
    //<![CDATA[  
    
    var $j = jQuery.noConflict();
    var cancelType = 0;
    var i = 0;
    $j(window).ready(function(){

        $j("#selectOrder").change( function() {
            var selectedOption = $j("#selectOrder option:selected");
            var selectedValue = selectedOption.val();
            if(selectedValue!=0)
            {        
                $j('#advice-validate-select-selectOrder').hide();
                $j.ajax({
                    type: "POST",
                    url: "<?php echo $this->getUrl('rma/index/productinfo')?>",
                    data: {OrderId:selectedValue},
                    success: function(response) {
                        if(response)
                        {
                            $j('#results').empty();
                            $j('#results').append(response);                    
                        }
                        else
                        {
                            $j('#results').append('Product cannot be return');
                        }                   
                    },
                    error: function() {
                        alert("error");
                    }
                });
            }
        }).trigger('change'); 

        $j("#requestForm").on('click', '#submit', function (e)
        {
            cnt=$j('#cnt').val();
            if(cancelType == 0)
            {
                var checked = $j('#my-rma-table').find(':checked').length;
                if(checked === 2)
                {
                    $j("#notification-message1").show();
                    $j("#notification1").empty();
                    $j("#notification1").append('Please select atleast one item');
                    e.stopImmediatePropagation();  
                    e.preventDefault();return;
                }
                else
                {
                $j("#notification-message1").hide();
                }
            }
            else
            {
                $j("#notification-message1").hide();
            }
            
            for (i = 0; i < cnt; i++) 
            {         
                var orderedQty = $j('.productQty').data('orderedqty');
                var productName = $j('.productQty').data('name');
                var qtyRequested = parseInt($j('.productQty').val());
                if(qtyRequested > orderedQty)
                {   
                    $j("#notification-message").show();
                    $j("#notification").empty();
                    $j("#notification").append("You can not return "+qtyRequested+" "+productName);
                    e.stopImmediatePropagation();
                    e.preventDefault();return;
                }
                else
                {
                    $j("#notification-message").hide();
                }
            }
        });
    var customForm = new VarienForm('requestForm'); 
    });
    //]]>
</script>