<div class="page-title">
    <h1>
    <?php
        $cancelType = $this->getCancelType();
        $rmaOrderId = $this->getRmaOrderId();
        $title = ($cancelType) ? $this->__('Cancel Order') : $this->__('Create RMA');
        echo $title;
    ?>
    </h1>
</div>
<form id="requestForm" method="POST" action="<?php echo Mage::getUrl('rma/index/save'); ?>">
    <label><h4>Order Id : </h4></label>
    <?php 
    $orderInfo = $this->getOrders();
    if(count($orderInfo)>0) : ?>
    <select name="order" id="selectOrder" class="validate-select">
    <option value="">-- Select Orders --</option>
    <?php
    $selected = '';
    foreach($orderInfo as $_order):
    if($rmaOrderId == $_order->getId()):
        $selected = 'selected';
    endif; 
    ?>
    <option value="<?php echo $_order->getId() ?>" <?php echo $selected;?>>
        <?php echo $_order->getIncrementId()?>
    </option>
    <?php endforeach;?>
    </select>
<?php endif; ?>
    <table class="data-table orders" id="my-rma-table" >
    <?php if(empty($cancelType)): ?>
    <col width="1" />
    <?php endif; ?>
    <col width="1" />
    <col width="1" />
    <col width="1" />
    <col width="1" />
    <thead>
        <tr>
            <?php if(empty($cancelType)): ?>
            <th class="view"><?php echo $this->__('ACTION'); ?></th>
            <?php endif; ?>
            <th class="number"><?php echo $this->__('PRODUCT NAME') ?></th>
            <th class=""><?php echo $this->__('SKU') ?></th>
            <th class="number"><?php echo $this->__('QUANTITY') ?></th>
            <th class="total"><span class="nobr"><?php echo $this->__('PRICE') ?></span></th>            
        </tr>
    </thead>
     
    <tbody id="results">
            
    </tbody>
     
    <tr>
        <td><label>Reason</label></td>
        <td><input type="text" name="reason" class="required-entry"></td>
    </tr>
    <tr style="display:none;">
        <td>&nbsp;</td>
        <td><input type="text" name="consign_number" readonly="readonly" value=""></td>
    </tr>
    <tr>
        <td>
            <input type="submit" id="submit">
        </td>
    </tr>
        
    </table>
    
</form>

<script type="text/javascript" >
    //<![CDATA[  
    
    var $j = jQuery.noConflict();
    var cancelType = 0;
    
    $j("#selectOrder").change( function() {
        var selectedOption = $j("#selectOrder option:selected");
        var selectedValue = selectedOption.val();
        if(selectedValue!=0)
        {        
            $j('#advice-validate-select-selectOrder').hide();
            $j.ajax({
                type: "POST",
                url: "<?php echo $this->getUrl('rma/index/productinfo')?>",
                data: {OrderId:selectedValue},
                success: function(response) {
                    if(response)
                    {
                        $j('#results').empty();
                        $j('#results').append(response);                    
                    }
                    else
                    {
                        $j('#results').append('Product cannot be return');
                    }                   
                },
                error: function() {
                    alert("error");
                }
            });
        }
    }).trigger('change'); 

    $j('#submit').click(function(){        
        cnt=$j('#cnt').val();  
        ncnt=cnt-1;
        
        for (i = 0; i < cnt; i++) 
        {            
            var selectedQtyById=$j('#productQty_'+i).val();
            var orderedQty = $j('#qty_ordered_'+i).val();            
            var product_name=$j("#product_name_"+i).val();              
              
            if(selectedQtyById > orderedQty)
            {   
                $j("#notification-message").show();
                $j("#notification").empty();
                $j("#notification").append("You can not return more than "+orderedQty+" "+product_name);
            }
        }
        
        if(cancelType ==0)
        {
            var checked = $j('#my-rma-table').find(':checked').length;
            if(checked === 2)
            {
                $j("#notification-message").show();
                $j("#notification").empty();
                $j("#notification").append('Please select atleast one item');
                
            }
        }
        else
        {
            $j("#notification-message").hide();
        }
    });
    var customForm = new VarienForm('requestForm'); 
    //]]>
</script>